name: pkgcheck

env:
  NOT_CRAN: FALSE

# This will cancel running jobs once a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  # Manually trigger the Action under Actions/pkgcheck
  workflow_dispatch:
  # Run on every push to main
  push:
    branches:
      - main
      - master

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check R version
        run: R --version
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'
      - name: Check R version
        run: R --version
      - name: Run pkgcheck
        uses: ropensci-review-tools/pkgcheck-action@v1.0.0
        with:
          summary-only: false
